import { precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// Ensure the service worker updates immediately
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Listen for Web Push events
self.addEventListener('push', (event) => {
  let data = {};
  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data = { body: event.data.text() };
    }
  }

  const title = data.title || 'OriNet Portal';
  const options = {
    body: data.body || 'Tienes una nueva notificacion',
    icon: '/orinet2.svg',
    badge: '/orinet2.svg',
    data: data.url || '/', // URL to open when clicked
  };

  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});

// Handle notification click to open the portal
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  const targetUrl = event.notification.data || '/';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window/tab open with the target URL
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url.includes(targetUrl) && 'focus' in client) {
          return client.focus();
        }
      }
      // If no window/tab is open, open a new one
      if (clients.openWindow) {
        return clients.openWindow(targetUrl);
      }
    })
  );
});
